// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgqmyqveqnvrmytmpbfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNncW15cXZlcW52cm15dG1wYmZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4OTYwMjMsImV4cCI6MjA5MDQ3MjAyM30.A_D8FOmSWTTGFocSIfE37AgWk1wVdh0_wdZMblvKl7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});